apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: mongodb
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongodb
  name: mongodb
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
